In [ ]:
import numpy as np
import pandas as pd

In [7]:
x = [1,2,3,5,1,2]
nx=np.array(x)

In [8]:
n4 = np.random.randint(1,10,100)
n4

array([3, 7, 6, 2, 1, 7, 3, 6, 5, 4, 6, 1, 2, 2, 4, 5, 2, 8, 7, 1, 8, 4,
       4, 3, 8, 1, 3, 4, 2, 8, 5, 9, 9, 6, 2, 3, 3, 1, 3, 6, 7, 9, 3, 2,
       9, 7, 6, 3, 3, 7, 3, 6, 9, 4, 1, 1, 6, 8, 1, 4, 1, 8, 4, 5, 8, 7,
       4, 2, 5, 9, 6, 7, 1, 1, 1, 2, 5, 1, 1, 8, 7, 8, 2, 6, 8, 7, 6, 4,
       3, 6, 5, 3, 1, 4, 6, 4, 8, 2, 5, 7])

In [9]:
n4.reshape((10,10))

array([[3, 7, 6, 2, 1, 7, 3, 6, 5, 4],
       [6, 1, 2, 2, 4, 5, 2, 8, 7, 1],
       [8, 4, 4, 3, 8, 1, 3, 4, 2, 8],
       [5, 9, 9, 6, 2, 3, 3, 1, 3, 6],
       [7, 9, 3, 2, 9, 7, 6, 3, 3, 7],
       [3, 6, 9, 4, 1, 1, 6, 8, 1, 4],
       [1, 8, 4, 5, 8, 7, 4, 2, 5, 9],
       [6, 7, 1, 1, 1, 2, 5, 1, 1, 8],
       [7, 8, 2, 6, 8, 7, 6, 4, 3, 6],
       [5, 3, 1, 4, 6, 4, 8, 2, 5, 7]])

In [11]:
n5 = n4.reshape((25,4))
n5

array([[3, 7, 6, 2],
       [1, 7, 3, 6],
       [5, 4, 6, 1],
       [2, 2, 4, 5],
       [2, 8, 7, 1],
       [8, 4, 4, 3],
       [8, 1, 3, 4],
       [2, 8, 5, 9],
       [9, 6, 2, 3],
       [3, 1, 3, 6],
       [7, 9, 3, 2],
       [9, 7, 6, 3],
       [3, 7, 3, 6],
       [9, 4, 1, 1],
       [6, 8, 1, 4],
       [1, 8, 4, 5],
       [8, 7, 4, 2],
       [5, 9, 6, 7],
       [1, 1, 1, 2],
       [5, 1, 1, 8],
       [7, 8, 2, 6],
       [8, 7, 6, 4],
       [3, 6, 5, 3],
       [1, 4, 6, 4],
       [8, 2, 5, 7]])

In [12]:
a = np.random.randint(1,100,(3,5))
b = np.random.randint(1,100,(3,2))
c = np.random.randint(1,100(2,3))
print(a)
print(b)
print(b)

<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\shruti\AppData\Local\Temp\ipykernel_8324\3735142411.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  c = np.random.randint(1,100(2,3))
C:\Users\shruti\AppData\Local\Temp\ipykernel_8324\3735142411.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  c = np.random.randint(1,100(2,3))
C:\Users\shruti\AppData\Local\Temp\ipykernel_8324\3735142411.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  c = np.random.randint(1,100(2,3))
C:\Users\shruti\AppData\Local\Temp\ipykernel_8324\3735142411.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  c = np.random.randint(1,100(2,3))


TypeError: 'int' object is not callable

In [14]:
np.hstack((a,b))

array([[89, 57, 58, 34, 26, 66, 22],
       [90, 78, 67, 87, 86, 36,  1],
       [66, 37, 97, 42, 97, 49, 79]])

In [16]:
np.vstack((a,b))

NameError: name 'T' is not defined

In [19]:
m = np.array([1,2,3,2,1,2,4,2,1,2,3,2,1,2,3,4,3,3,4,3,3])

In [20]:
#boolen filter
m > 5

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [21]:
m[m>1]

array([2, 3, 2, 2, 4, 2, 2, 3, 2, 2, 3, 4, 3, 3, 4, 3, 3])

In [22]:
m[m !=2]

array([1, 3, 1, 4, 1, 3, 1, 3, 4, 3, 3, 4, 3, 3])

In [23]:
#in range of 2 to 8
m[(m>1) & (m<4)]

array([2, 3, 2, 2, 2, 2, 3, 2, 2, 3, 3, 3, 3, 3])

In [24]:
mat = []
for i in range(10):
    mat.append(int(input('Enter number')))
mat = np.array(mat)


In [ ]:
print(mat,mat.shape4)