In [34]:
import numpy as np
import pandas as pd

In [35]:
x =[1,2,3,4,1,2]
nx = np.array(x)

In [36]:
print(nx)

[1 2 3 4 1 2]


In [37]:
print(nx.shape)

(6,)


In [38]:
ny = np.array([[1,2,3],[5,6,7]])

In [39]:
print(ny.shape)

(2, 3)


In [40]:
ny

array([[1, 2, 3],
       [5, 6, 7]])

In [41]:
one = np.arange(1,100,.2)
print(one)

[ 1.   1.2  1.4  1.6  1.8  2.   2.2  2.4  2.6  2.8  3.   3.2  3.4  3.6
  3.8  4.   4.2  4.4  4.6  4.8  5.   5.2  5.4  5.6  5.8  6.   6.2  6.4
  6.6  6.8  7.   7.2  7.4  7.6  7.8  8.   8.2  8.4  8.6  8.8  9.   9.2
  9.4  9.6  9.8 10.  10.2 10.4 10.6 10.8 11.  11.2 11.4 11.6 11.8 12.
 12.2 12.4 12.6 12.8 13.  13.2 13.4 13.6 13.8 14.  14.2 14.4 14.6 14.8
 15.  15.2 15.4 15.6 15.8 16.  16.2 16.4 16.6 16.8 17.  17.2 17.4 17.6
 17.8 18.  18.2 18.4 18.6 18.8 19.  19.2 19.4 19.6 19.8 20.  20.2 20.4
 20.6 20.8 21.  21.2 21.4 21.6 21.8 22.  22.2 22.4 22.6 22.8 23.  23.2
 23.4 23.6 23.8 24.  24.2 24.4 24.6 24.8 25.  25.2 25.4 25.6 25.8 26.
 26.2 26.4 26.6 26.8 27.  27.2 27.4 27.6 27.8 28.  28.2 28.4 28.6 28.8
 29.  29.2 29.4 29.6 29.8 30.  30.2 30.4 30.6 30.8 31.  31.2 31.4 31.6
 31.8 32.  32.2 32.4 32.6 32.8 33.  33.2 33.4 33.6 33.8 34.  34.2 34.4
 34.6 34.8 35.  35.2 35.4 35.6 35.8 36.  36.2 36.4 36.6 36.8 37.  37.2
 37.4 37.6 37.8 38.  38.2 38.4 38.6 38.8 39.  39.2 39.4 39.6 39.8 40.
 40.2 40.

In [42]:
print(one.size)

495


In [43]:
two = np.linspace(1,100,200)
two

array([  1.        ,   1.49748744,   1.99497487,   2.49246231,
         2.98994975,   3.48743719,   3.98492462,   4.48241206,
         4.9798995 ,   5.47738693,   5.97487437,   6.47236181,
         6.96984925,   7.46733668,   7.96482412,   8.46231156,
         8.95979899,   9.45728643,   9.95477387,  10.45226131,
        10.94974874,  11.44723618,  11.94472362,  12.44221106,
        12.93969849,  13.43718593,  13.93467337,  14.4321608 ,
        14.92964824,  15.42713568,  15.92462312,  16.42211055,
        16.91959799,  17.41708543,  17.91457286,  18.4120603 ,
        18.90954774,  19.40703518,  19.90452261,  20.40201005,
        20.89949749,  21.39698492,  21.89447236,  22.3919598 ,
        22.88944724,  23.38693467,  23.88442211,  24.38190955,
        24.87939698,  25.37688442,  25.87437186,  26.3718593 ,
        26.86934673,  27.36683417,  27.86432161,  28.36180905,
        28.85929648,  29.35678392,  29.85427136,  30.35175879,
        30.84924623,  31.34673367,  31.84422111,  32.34

In [44]:
print(two.size)

200


In [45]:
n3 = np.random.rand(100)
n3

array([0.41196048, 0.96687955, 0.35025783, 0.2259161 , 0.41701587,
       0.16573115, 0.48012202, 0.3158642 , 0.60812871, 0.64739964,
       0.75238351, 0.00925954, 0.26316512, 0.22716164, 0.19349747,
       0.88199569, 0.22450449, 0.54248172, 0.14302402, 0.24053272,
       0.49397706, 0.59430104, 0.36447044, 0.64674174, 0.39322158,
       0.11551327, 0.87291219, 0.00938867, 0.74787754, 0.23784945,
       0.79361248, 0.91617267, 0.38546673, 0.30508191, 0.15114768,
       0.8932841 , 0.0680916 , 0.93439118, 0.13903902, 0.8461067 ,
       0.50722232, 0.8567407 , 0.98914081, 0.6833441 , 0.51996947,
       0.95154459, 0.94360608, 0.92258405, 0.06054919, 0.48510655,
       0.54080013, 0.39483977, 0.98936583, 0.92094662, 0.46619439,
       0.95999397, 0.43504923, 0.04561815, 0.74708731, 0.82798324,
       0.84971744, 0.37944786, 0.53461736, 0.66469184, 0.50056184,
       0.74985615, 0.76658204, 0.59030544, 0.11866818, 0.13072366,
       0.39713973, 0.30416772, 0.00945737, 0.95175123, 0.42379

In [46]:
n4 = np.random.randint(1,10,100)
n4

array([4, 1, 8, 3, 1, 2, 4, 1, 8, 5, 2, 2, 3, 4, 4, 9, 8, 5, 5, 2, 6, 4,
       5, 3, 6, 1, 2, 6, 6, 5, 6, 6, 1, 4, 3, 6, 4, 8, 2, 9, 3, 9, 3, 7,
       5, 2, 2, 7, 2, 6, 8, 4, 6, 4, 7, 4, 8, 5, 7, 4, 8, 5, 3, 4, 3, 5,
       1, 3, 3, 5, 4, 8, 5, 8, 7, 6, 9, 3, 6, 3, 3, 6, 9, 6, 2, 5, 2, 2,
       9, 3, 9, 5, 8, 6, 1, 2, 8, 7, 3, 2])

In [47]:
n4.reshape((10,10))

array([[4, 1, 8, 3, 1, 2, 4, 1, 8, 5],
       [2, 2, 3, 4, 4, 9, 8, 5, 5, 2],
       [6, 4, 5, 3, 6, 1, 2, 6, 6, 5],
       [6, 6, 1, 4, 3, 6, 4, 8, 2, 9],
       [3, 9, 3, 7, 5, 2, 2, 7, 2, 6],
       [8, 4, 6, 4, 7, 4, 8, 5, 7, 4],
       [8, 5, 3, 4, 3, 5, 1, 3, 3, 5],
       [4, 8, 5, 8, 7, 6, 9, 3, 6, 3],
       [3, 6, 9, 6, 2, 5, 2, 2, 9, 3],
       [9, 5, 8, 6, 1, 2, 8, 7, 3, 2]])

In [48]:
n4.reshape((10,5,2))


array([[[4, 1],
        [8, 3],
        [1, 2],
        [4, 1],
        [8, 5]],

       [[2, 2],
        [3, 4],
        [4, 9],
        [8, 5],
        [5, 2]],

       [[6, 4],
        [5, 3],
        [6, 1],
        [2, 6],
        [6, 5]],

       [[6, 6],
        [1, 4],
        [3, 6],
        [4, 8],
        [2, 9]],

       [[3, 9],
        [3, 7],
        [5, 2],
        [2, 7],
        [2, 6]],

       [[8, 4],
        [6, 4],
        [7, 4],
        [8, 5],
        [7, 4]],

       [[8, 5],
        [3, 4],
        [3, 5],
        [1, 3],
        [3, 5]],

       [[4, 8],
        [5, 8],
        [7, 6],
        [9, 3],
        [6, 3]],

       [[3, 6],
        [9, 6],
        [2, 5],
        [2, 2],
        [9, 3]],

       [[9, 5],
        [8, 6],
        [1, 2],
        [8, 7],
        [3, 2]]])

In [49]:
n5 = n4.reshape(25,4)
n5

array([[4, 1, 8, 3],
       [1, 2, 4, 1],
       [8, 5, 2, 2],
       [3, 4, 4, 9],
       [8, 5, 5, 2],
       [6, 4, 5, 3],
       [6, 1, 2, 6],
       [6, 5, 6, 6],
       [1, 4, 3, 6],
       [4, 8, 2, 9],
       [3, 9, 3, 7],
       [5, 2, 2, 7],
       [2, 6, 8, 4],
       [6, 4, 7, 4],
       [8, 5, 7, 4],
       [8, 5, 3, 4],
       [3, 5, 1, 3],
       [3, 5, 4, 8],
       [5, 8, 7, 6],
       [9, 3, 6, 3],
       [3, 6, 9, 6],
       [2, 5, 2, 2],
       [9, 3, 9, 5],
       [8, 6, 1, 2],
       [8, 7, 3, 2]])

In [50]:
n1 = np.random.randint(1,10,(5,5))
n2 = np.random.randint(1,10,(5,5))

In [51]:
n1 + n2

array([[11,  7, 11,  8,  7],
       [12, 11,  9, 15, 11],
       [13, 10,  9, 16, 13],
       [ 6,  5,  7, 12,  7],
       [ 4, 10, 11,  9, 16]])

In [52]:
n1 ** n2

array([[     512,       64,     6561,      125,       81],
       [   65536,    15625,        1,  5764801,     7776],
       [   32768,     1296,      729, 40353607,   390625],
       [      16,        4,       81,    19683,        1],
       [       4,     2187,      512,        1,  4782969]])

In [53]:
n1 * 4

array([[32, 16, 12, 20, 12],
       [16, 20,  4, 28, 24],
       [32, 24, 12, 28, 20],
       [ 8, 16, 12, 12,  4],
       [ 8, 12, 32,  4, 36]])

In [54]:
n1.dot(n2)

array([[ 97,  86, 143, 152, 127],
       [ 97,  95, 124, 172, 133],
       [125, 114, 173, 202, 163],
       [ 67,  52,  81, 100,  77],
       [ 92, 120, 119, 183, 156]])

In [55]:
n6 = np.random.randint(1,10,10)
n6

array([1, 8, 8, 6, 1, 6, 9, 4, 5, 8])

In [56]:
n6[-1]

8

In [57]:
n6[:5]

array([1, 8, 8, 6, 1])

In [61]:
n6[4:5]

array([1])

In [59]:
#flatter a n dimen matrix to 1 dimen matrix
n5.flatten()

array([4, 1, 8, 3, 1, 2, 4, 1, 8, 5, 2, 2, 3, 4, 4, 9, 8, 5, 5, 2, 6, 4,
       5, 3, 6, 1, 2, 6, 6, 5, 6, 6, 1, 4, 3, 6, 4, 8, 2, 9, 3, 9, 3, 7,
       5, 2, 2, 7, 2, 6, 8, 4, 6, 4, 7, 4, 8, 5, 7, 4, 8, 5, 3, 4, 3, 5,
       1, 3, 3, 5, 4, 8, 5, 8, 7, 6, 9, 3, 6, 3, 3, 6, 9, 6, 2, 5, 2, 2,
       9, 3, 9, 5, 8, 6, 1, 2, 8, 7, 3, 2])

In [63]:
x = np.random.randint(1,10,(5,5))
print(x)

[[4 2 1 2 8]
 [3 8 6 9 3]
 [1 4 5 2 2]
 [6 8 9 6 4]
 [1 6 5 6 6]]


In [65]:
x.transpose()#transpose is row to column and column to row

array([[4, 3, 1, 6, 1],
       [2, 8, 4, 8, 6],
       [1, 6, 5, 9, 5],
       [2, 9, 2, 6, 6],
       [8, 3, 2, 4, 6]])

In [66]:
n6

array([1, 8, 8, 6, 1, 6, 9, 4, 5, 8])

In [68]:
n6.mean()

5.6

In [70]:
n6.sum()

56

In [71]:
n6.max()

9

In [72]:
print(n6, n6.max(),"found at index", n6.argmax())
print(n6, n6.min(),"found at index", n6.argmin())

[1 8 8 6 1 6 9 4 5 8] 9 found at index 6
[1 8 8 6 1 6 9 4 5 8] 1 found at index 0


In [73]:
a = np.random.randint(1,100, (3,2))
b = np.random.randint(1,100, (3,2))
c = np.random.randint(1,100, (2,3))

print(a)
print(b)
print(c)

[[43 19]
 [ 2 41]
 [ 9 93]]
[[19 83]
 [ 7 73]
 [20 42]]
[[71 15 91]
 [42 77 53]]


In [74]:
np.hstack((a,b)) # horizontal stack

array([[43, 19, 19, 83],
       [ 2, 41,  7, 73],
       [ 9, 93, 20, 42]])

In [75]:
np.vstack((a, c.T))

array([[43, 19],
       [ 2, 41],
       [ 9, 93],
       [71, 42],
       [15, 77],
       [91, 53]])

In [76]:
m = np.array([1,2,3,4,2,2,3,5,6,1,2,2,3,5,6,1,2,3,5,6,2,4,5,6,3,1,2,3,5,7,6,8,9])


In [77]:
# boolean filter
m > 5

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False, False, False,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True,  True,  True,  True])

In [78]:
m[m != 2]

array([1, 3, 4, 3, 5, 6, 1, 3, 5, 6, 1, 3, 5, 6, 4, 5, 6, 3, 1, 3, 5, 7,
       6, 8, 9])

In [79]:
# in range of 2 to 8
m[(m > 2) & (m < 8)]

array([3, 4, 3, 5, 6, 3, 5, 6, 3, 5, 6, 4, 5, 6, 3, 3, 5, 7, 6])

In [81]:
mat = []
for i in range(10):
    mat.append(int(input('Enter value')))
mat = np.array(mat)

In [82]:
mat

array([3, 4, 3, 4, 6, 7, 5, 9, 6, 6])

In [83]:
print(mat, mat.shape)

[3 4 3 4 6 7 5 9 6 6] (10,)


In [84]:
# user created numpy matrix
mat= []
for i in range(2):
    smat = []
    for j in range(3):
        smat.append(int(input('Enter value')))
    mat.append(smat)
mat = np.array(mat)
print(mat, mat.shape)

[[4 3 5]
 [7 8 2]] (2, 3)
